#include "idt.h"
#include "lib.h"
#include "i8259.h"
#include "rtc.h"
#include "x86_desc.h"
#include "systemcalls.h"

extern int32_t system_halt(uint8_t status);

void init_idt() {

    // Check the pages 5-22 ~ 5-59 of ISA Reference Manual for IDT implementation

    // Interrupt 0 - Divide Error Exception (#DE)
    //
    //      Exception Class: Fault.
    //          Description: Indicates the divisor operand for a DIV or IDIV
    //                       instruction is 0 or that the result cannot be
    //                       represented in the number of bits specified for the
    //                       destination operand.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x00], divide_error_exception, TRAP_IDT);

    // Interrupt 1 - Debug Exception (#DB)
    //
    //      Exception Class: Trap or Fault.
    //          Description: Indicates that one or more of several debug-exception
    //                       conditions has been detected. Whether the exception is
    //                       a fault or a trap depends on the condition.
    //                       Check Table 5-3 in page 5-24 for further details.
    // Exception Error Code: None.
    //                       An exception handler can examine the debug registers
    //                       to determine which condition caused the exception.
    SET_IDT_ENTRY(idt[0x01], debug_exception,TRAP_IDT);

    // Interrupt 2 - NMI Interrupt
    //
    //      Exception Class: Not applicable.
    //          Description: The nonmaskable interrupt (NMI) is generated externally
    //                       by asserting the processor’s NMI pin or through an
    //                       NMI request set by the I/O APIC to the local APIC.
    //                       This interrupt causes the NMI interrupt handler
    //                       to be called.
    // Exception Error Code: Not applicable.
    SET_IDT_ENTRY(idt[0x02], nmi_interrupt, INTERRUPT_IDT);

    // Interrupt 3 - Breakpoint Exception (#BP)
    //
    //      Exception Class: Trap.
    //          Description: Indicates that a breakpoint instruction (INT 3) was
    //                       executed, causing a breakpoint trap to be generated.
    //                       The breakpoint (#BP) exception can also be generated by
    //                       executing the INT n instruction with an operand of 3.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x03], breakpoint_exception, TRAP_IDT);

    // Interrupt 4 - Overflow Exception (#OF)
    //
    //      Exception Class: Trap.
    //          Description: Indicates that an overflow trap occurred when an
    //                       INTO instruction was executed.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x04], overflow_exception, TRAP_IDT);

    // Interrupt 5 - BOUND Range Exceeded Exception (#BR)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that a BOUND-range-exceeded fault occurred
    //                       when a BOUND instruction was executed.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x05], bound_range_exceeded_exception, TRAP_IDT);

    // Interrupt 6 - Invalid Opcode Exception(#UD)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that processor attempted to execute
    //                       something wrongly. Check page 5-29 for further details.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x06], invalid_opcode_exception, TRAP_IDT);

    // Interrupt 7 - Device Not Available Exception (#NM)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that processor attempted to execute
    //                       something wrongly. Check page 5-31 for further details.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x07], device_not_available_exception, TRAP_IDT);

    // Interrupt 8 - Double Fault Exception (#DF)
    //
    //      Exception Class: Abort.
    //          Description: Indicates that the processor detected a second exception
    //                       while calling an exception handler for a prior exception.
    // Exception Error Code: Zero. The processor always pushes an error code 0
    //                       onto the stack of the double-fault handler.
    SET_IDT_ENTRY(idt[0x08], double_fault_exception, TRAP_IDT);

    // Interrupt 9 - Coprocessor Segment Overrun
    //
    //      Exception Class: Abort.
    //          Description: Indicates that an Intel 386 CPU-based systems with an
    //                       Intel 387 math coprocessor detected a page or segment
    //                       violation while transferring the middle portion of
    //                       an Intel 387 math coprocessor operand.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x09], coprocessor_segment_overrun, TRAP_IDT);

    // Interrupt 10 - Invalid TSS Exception (#TS)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that there was an error related to a TSS.
    //                       Check Table 5-6 in page 5-36 ~ 5-37 for further details.
    // Exception Error Code: An error code containing the segment selector index
    //                       for the segment descriptor that caused the violation
    //                       is pushed onto the stack of the exception handler.
    SET_IDT_ENTRY(idt[0x0A], invalid_tss_exception, TRAP_IDT);

    // Interrupt 11 - Segment Not Present (#NP)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that the present flag of a segment or gate
    //                       descriptor is clear.
    // Exception Error Code: An error code containing the segment selector index
    //                       for the segment descriptor that caused the violation
    //                       is pushed onto the stack of the exception handler.
    SET_IDT_ENTRY(idt[0x0B], segment_not_present, TRAP_IDT);

    // Interrupt 12 - Stack Fault Exception (#SS)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that stack related conditions was detected.
    //                       Check page 5-44 for further details.
    // Exception Error Code: An error code containing the segment selector index
    //                       for the segment descriptor that caused the violation
    //                       if the exception is caused by a not-present stack
    //                       segment or by oveflow of the new stack during an
    //                       inter-privilege-level call.
    SET_IDT_ENTRY(idt[0x0C], stack_fault_exception, TRAP_IDT);

    // Interrupt 13 - General Protection Exception (#GP)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that the processor detected one of
    //                       a class of protection violations called
    //                       “general-protection violations.”
    //                       Check page 5-43 ~ 5-44 for further details.
    // Exception Error Code: If the fault condition was detected while loading a
    //                       segment descriptor, the error code contains a
    //                       segment selector to or IDT vector number for the
    //                       descriptor; otherwise, the error code is 0.
    SET_IDT_ENTRY(idt[0x0D], general_protection_exception, TRAP_IDT);

    // Interrupt 14 - Page-Fault Exception (#PF)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that, with paging enabled (the PG flag in
    //                       the CR0 register is set), the processor detected some
    //                       conditions while using the page-translation mechanism
    //                       to translate a linear address to a physical address.
    //                       Check page 5-46 ~ 5-49 for further details.
    // Exception Error Code: Yes (special format).
    SET_IDT_ENTRY(idt[0x0E], page_fault_exception, TRAP_IDT);

    // Interrupt 15 is reserved by Intel (known to related to temperature)
    // SET_IDT_ENTRY(idt[0x0F], spurious_interrupt);

    // Interrupt 16 - x87_floating_point_error (#PF)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that the x87 FPU has
    //                       detected a floating-point error
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x10], x87_floating_point_error, TRAP_IDT);

    // Interrupt 17 - Alignment Check Exception (#AC)
    //
    //      Exception Class: Fault.
    //          Description: Indicates that the x87 FPU has detected an unaligned
    //                       memory operand when alignment checking was enabled.
    // Exception Error Code: Yes (always zero).
    SET_IDT_ENTRY(idt[0x11], alignment_check_exception, TRAP_IDT);

    // Interrupt 18 - Machine-Check Exception (#MC)
    //
    //      Exception Class: Abort.
    //          Description: Indicates that the the processor detected an internal
    //                       machine error or a bus error, or that an external agent
    //                       agent detected a bus error.
    // Exception Error Code: None. Error information is provide by machine-check MSRs.
    SET_IDT_ENTRY(idt[0x12], machine_check_exception, TRAP_IDT);

    // Interrupt 19 - SIMD Floating-Point Exception (#XF)
    //
    //      Exception Class: Fault.
    //          Description: Indicates the processor has detected an SSE/SSE2/SSE3
    //                       SIMD floating-point exception.
    // Exception Error Code: None.
    SET_IDT_ENTRY(idt[0x13], simd_floating_point_exception, TRAP_IDT);

    // SET_IDT_ENTRY(idt[0x14], virtualization_exception);
    // SET_IDT_ENTRY(idt[0x15], control_protection_exception);

    // Interrupt 21 is reserved by Intel

    // Interrupts 32 to 255 - User Defined Interupts
    // int idt_index;
    // for(idt_index = 32; i < 256; ++i)
    // {
    //     SET_IDT_ENTRY(idt[idt_index], user_defined_interrupts)
    // }

    // Interrupt 32 - PIT interrupt
    SET_IDT_ENTRY(idt[0x20], scheduler_wrapper, INTERRUPT_IDT);

    // Interrupt 33 - Keyboard interrupt
    SET_IDT_ENTRY(idt[0x21], keyboard_wrapper, INTERRUPT_IDT);

    // Interrupt 40 - RTC interrupt
    SET_IDT_ENTRY(idt[0x28], rtc_wrapper, INTERRUPT_IDT);

    // Interrupt 128 - System call
    SET_IDT_ENTRY(idt[0x80], system_call_wrapper, SYS_IDT);

    lidt(idt_desc_ptr);
}

/*
 * void divide_error_exception(void)
 *   Inputs: void
 * Function: handles divide error exception
 */
void divide_error_exception(void)
{
    cli();
    clear();
    puts("FAULT: Divsor operand for a DIV or IDIV instruction is 0.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void debug_exception(void)
 *   Inputs: void
 * Function: handles debug exception
 */
void debug_exception(void)
{
    cli();
    clear();
    puts("ERROR: One or more of several debug-exception conditions has been detected.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void nmi_interrupt(void)
 *   Inputs: void
 * Function: handles nonmaskable ineterrupt (NMI).
 */
void nmi_interrupt(void)
{
    cli();
    clear();
    puts("INTERRUPT: The nonmaskable interrupt (NMI) is generated externally.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void breakpoint_exception(void)
 *   Inputs: void
 * Function: handles breakpoint exception
 */
void breakpoint_exception(void)
{
    cli();
    clear();
    puts("TRAP: Breakpoint instruction (INT 3) was executed, causing a breakpoint trap to be generated.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void overflow_exception(void)
 *   Inputs: void
 * Function: handles overflow exception
 */
void overflow_exception(void)
{
    cli();
    clear();
    puts("TRAP: An overflow trap occurred when an INO instruction was executed.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void bound_range_exceeded_exception(void)
 *   Inputs: void
 * Function: handles BOUTN-range-exceeded excpetion
 */
void bound_range_exceeded_exception(void)
{
    cli();
    clear();
    puts("FAULT: A BOUND-range-exceeded fault occurred when a BOUNT instruction was executed.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void invalid_opcode_exception(void)
 *   Inputs: void
 * Function: handles invalid opcode exception
 */
void invalid_opcode_exception(void)
{
    cli();
    clear();
    puts("FAULT: Invalid opcode exception occurred.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void device_not_available_exception(void)
 *   Inputs: void
 * Function: handles device-not-available exception
 */
void device_not_available_exception(void)
{
    cli();
    clear();
    puts("FAULT: Device not available.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void double_fault_exception(void)
 *   Inputs: void
 * Function: handles double-fault exception
 */
void double_fault_exception(void)
{
    cli();
    clear();
    puts("ABORT: The processor detected a second exception while calling an exception handler for a prior exception.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

// ! this exception is Intel reserved, Recent IA-32 processors do not generate this exception.

/*
 * void coprocessor_segment_overrun(void)
 *   Inputs: void
 * Function: handles coprocessor segment overrun issue.
 */
void coprocessor_segment_overrun(void)
{
    cli();
    clear();
    puts("ABORT: A math coprocessor detected a page or segment violation hile transferring the middle portion of operand.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void invalid_tss_exception(void)
 *   Inputs: void
 * Function: handles invalid TSS exception
 */
void invalid_tss_exception(void)
{
    cli();
    clear();
    puts("FAULT: There was an error related to a TSS.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void segment_not_present(void)
 *   Inputs: void
 * Function: handles SNP exception
 */
void segment_not_present(void)
{
    cli();
    clear();
    puts("FAULT: The present flag of a segment or gate descriptor is clear.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void stack_fault_exception(void)
 *   Inputs: void
 * Function: handles stack fault exception
 */
void stack_fault_exception(void)
{
    cli();
    clear();
    puts("FAULT: A stack related conditions was detected.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void general_protection_exception(void)
 *   Inputs: void
 * Function: handles general protection exception
 */
void general_protection_exception(void)
{
    cli();
    clear();
    puts("FAULT: The processor detected general protection violation, one of a class of protection violations.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void page_fault_exception(void)
 *   Inputs: void
 * Function: handles page-fault excpetion
 */
void page_fault_exception(void)
{
    cli();
    // clear();
    puts("FAULT: The processor detected one of the conditions with paging enabled.\n");
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void RESERVED_BY_INTEL(void)
 * {
 *
 * }
 */

/*
 * void x87_floating_point_error(void)
 *   Inputs: void
 * Function: handles x87 FPU floating-point error
 */
void x87_floating_point_error(void)
{
    cli();
    clear();
    puts("FAULT: x87 CPU has detected a floating-point error.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void alignment_check_exception(void)
 *   Inputs: void
 * Function: handles alignment check exception
 */
void alignment_check_exception(void)
{
    cli();
    clear();
    puts("FAULT: The processor detected an unaligned memory operand when alignment checking was enabled.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void divide_error_exception(void)
 *   Inputs: void
 * Function: handles NMI ineterrups
 */
void machine_check_exception(void)
{
    cli();
    clear();
    puts("ABORT: The processor detected an internal machine error or a bus error.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}

/*
 * void divide_error_exception(void)
 *   Inputs: void
 * Function: handles NMI ineterrups
 */
void simd_floating_point_exception(void)
{
    cli();
    clear();
    puts("FAULT: The processor has detected an SSE/SSE2/SSE3 SIMD floating-point exception.\n");
    // while(1);
    sti();
    set_exception_one();
    system_halt(0);
}
