boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt.o: interrupt.S
x86_desc.o: x86_desc.S x86_desc.h types.h
devicekeyboard.o: devicekeyboard.c devicekeyboard.h lib.h types.h i8259.h \
  terminal.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h i8259.h rtc.h x86_desc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h rtc.h paging.h devicekeyboard.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c lib.h types.h terminal.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h terminal.h
